remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme

title: "Jerónimo García-Mejía"
author: "Jerónimo García-Mejía"
description: "Jerónimo García-Mejía <small>(he/him/his, they/them/theirs)</small> "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  # - {file: "index.md", title: "Home"}
  - {file: "research.md", titel: "Research"}
  - {file: "teaching.md", title: "Teaching"} 
  - {file: "contact.md", title: "Contact"}
  - {file: "misc.md", title: "Miscellaneous"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons + Academicons
  - {title: Mail, icon: envelope, url: "mailto:jeronimo.garcia-mejia@warwick.ac.uk"}
  - {titel: arXiv, icon: arxiv, url: "http://arxiv.org/a/garciamejia_j_1"}
  - {title: ORCiD, icon: orcid, url: "https://orcid.org/0009-0008-7026-6548"}
  #- {title: Github, icon: github, url: "https://github.com/jeronimomaths"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jemoji
 
markdown: redcarpet

#kramdown:
  #input: Kramdown
  #allows open link in new tabs by inserting {:target="_blank" rel="noopener"}
